services:
    creavio.image_manager:
        class: Creavio\ImageManageBundle\Util\ImageManager
        arguments: ["@service_container"]

    creavio.twig.image_manage_extension:
        class: Creavio\ImageManageBundle\Twig\Extension\ImageManageExtension
        arguments: ["@service_container"]
        tags: [{ name: twig.extension }]