services:
    _defaults:
        public: true
        autowire: true

    creavio.image_manager:
        class: Creavio\ImageManageBundle\Util\ImageManager
    Creavio\ImageManageBundle\Util\ImageManager: '@creavio.image_manager'

    Creavio\ImageManageBundle\Twig\Extension\ImageManageExtension:
        tags: [{ name: twig.extension }]